# Generated by Django 5.0.6 on 2024-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='email',
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='inst_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='swift_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
